services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  web:
    build:
      context: ./simarte_rails
      dockerfile: Dockerfile.dev
    #command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    command: ./bin/dev
    volumes:
      - ./simarte_rails:/app
      - bundle_data:/usr/local/bundle
    working_dir: /app
    ports:
      - "3000:3000"
    tty: true
    stdin_open: true
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      REDIS_URL: ${REDIS_URL}
      TAILWIND_WATCHER_POLLING: true
      AUTH0_DOMAIN: dev-42qe53otnaih34xb.us.auth0.com
      AUTH0_AUDIENCE: https://api.simarte.co.za
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  sidekiq:
    build:
      context: ./simarte_rails
      dockerfile: Dockerfile.dev
    command: bundle exec sidekiq
    volumes:
      - ./simarte_rails:/app
      - bundle_data:/usr/local/bundle
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      REDIS_URL: ${REDIS_URL}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  bundle_data:
  simarte_rails:
